spring.application.name=Job Recommendation System
spring.datasource.url=jdbc:postgresql://localhost:5432/jobrecommendation
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
logging.level.org.springframework.security=DEBUG
jwt.secret=rNRKh2M3cEjTXdhDEmAH7DLBvuHRG1FvHYnd5uWVK4+FAp4R5HH7Kfj6TR2kW6+rMG48qTt2MLzEVWzKh1OnIA==
jwt.expiration=86400000